/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TextDetection } from "./TextDetection";
import { TextDetectionCountArgs } from "./TextDetectionCountArgs";
import { TextDetectionFindManyArgs } from "./TextDetectionFindManyArgs";
import { TextDetectionFindUniqueArgs } from "./TextDetectionFindUniqueArgs";
import { DeleteTextDetectionArgs } from "./DeleteTextDetectionArgs";
import { TextDetectionService } from "../textDetection.service";
@graphql.Resolver(() => TextDetection)
export class TextDetectionResolverBase {
  constructor(protected readonly service: TextDetectionService) {}

  async _textDetectionsMeta(
    @graphql.Args() args: TextDetectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TextDetection])
  async textDetections(
    @graphql.Args() args: TextDetectionFindManyArgs
  ): Promise<TextDetection[]> {
    return this.service.textDetections(args);
  }

  @graphql.Query(() => TextDetection, { nullable: true })
  async textDetection(
    @graphql.Args() args: TextDetectionFindUniqueArgs
  ): Promise<TextDetection | null> {
    const result = await this.service.textDetection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TextDetection)
  async deleteTextDetection(
    @graphql.Args() args: DeleteTextDetectionArgs
  ): Promise<TextDetection | null> {
    try {
      return await this.service.deleteTextDetection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
